RD ".vs" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.ConstantExpectedAttribute\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.ConstantExpectedAttribute\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.DynamicallyAccessedMembersAttribute\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.DynamicallyAccessedMembersAttribute\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.ExcludeFromCodeCoverageAttribute\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.ExcludeFromCodeCoverageAttribute\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.ExtensionAttribute\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.ExtensionAttribute\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.FuncAction.G2\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.FuncAction.G2\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.FuncAction.G3\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.FuncAction.G3\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.GuidAttribute\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.GuidAttribute\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.LoaderOptimizationAttribute\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.LoaderOptimizationAttribute\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.NullableReferenceTypeAttributes.G1\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.NullableReferenceTypeAttributes.G1\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.NullableReferenceTypeAttributes.G2\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.NullableReferenceTypeAttributes.G2\bin" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.NullableReferenceTypeAttributes.G3\obj" /S /Q 2>nul
RD "C:\Source\Prod\Hafner.Compatibility.Packages\Source\Hafner.Compatibility.NullableReferenceTypeAttributes.G3\bin" /S /Q 2>nul